### ISSUE TITLE
terraform: add modules to support Azure

### ISSUE THREAD

**Issue by moio** [moio/scalability-tests#19]
- [x] add support to create network, bastion, vms
- [x] add support for a minimal main setup (eg. k3s upstream, 3 k3s clusters downstream)
- [x] add support to RKE2
- [x] add support to AKS

**Comment by fgiudici** [comment]
WiP draft branch https://github.com/moio/scalability-tests/pull/18

**Comment by pgonin** [comment]
priorities => RKE2 support &  test RKE2 vs AKS (and dependencies)

**Comment by fgiudici** [comment]
#18 - Initial Azure deployment (VMs and k3s)

**Comment by moio** [comment]
Moving RKE2 vs AKS to separate issue, closing this one
