### ISSUE TITLE
Port scripts in bin/ to Golang

### ISSUE THREAD

**Issue by moio** [moio/scalability-tests#39]
In high-scale scenarios (100+ clusters) some operations such as cluster import will benefit from parallelization.

There is no intention to implement that on the current Javascript code, therefore intention is to port those scripts to Golang.

**Comment by fgiudici** [comment]
Split in two sub-issues:
- [ ] https://github.com/moio/scalability-tests/issues/46
- [ ] https://github.com/moio/scalability-tests/issues/47
